src/Entity/Projet.php
<?php

namespace App\Entity;

use App\Repository\ProjetRepository;
use Doctrine\ORM\Mapping as ORM;
#[ORM\Entity(repositoryClass: ProjetRepository::class)]
#[ORM\Table(name:"projects")]
#[ORM\HasLifecycleCallbacks]

class Projet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type:"datetime", options:["default"=> "CURRENT_TIMESTAMP"])]
    private $start_date;

    #[ORM\Column(type:"datetime", options:["default"=> "CURRENT_TIMESTAMP"])]
    private $end_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }
    #[ORM\PrePersist]                
    #[ORM\PreUpdate]    
    public function updateTimestamps()
    {
        if ($this->getEndDate() === null) {
            $this->setStartDate(new \DateTimeImmutable);
        }
        $this->setEndDate(new \DateTimeImmutable);
    }
}

src/Form/ProjetType.php
<?php

namespace App\Form;

use App\Entity\Projet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projet::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;
use App\Entity\Projet;
use App\Repository\ProjetRepository;
use App\Form\ProjetType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityManagerInterface;

class ProjectController extends AbstractController
{
    #[Route('/ ', name: 'app_home')]
    public function index(ManagerRegistry $doctrine, ProjetRepository $repo): Response
    {
       

    return $this->render('project/index.html.twig', ['projects' => $repo->findAll()]);
    }
    #[Route('/project/{id<[0-9]+>}', name:'app_projet_show', methods:'GET')]
    public function show(Projet $projet): Response
    {
        return $this->render('project/show.html.twig', compact('projet'));
    }  
    #[Route("/project/create", name:"app_projet_create", methods: ["GET","POST"])]
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $projet = new Projet;
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($projet);
            $em->flush();
            return $this->redirectToRoute('app_home');
        }
        return $this->render('project/create.html.twig', ['monForm' => $form->createView()]);   
       }  
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/project/_form.html.twig
{{ form_start(monForm) }}
{{ form_widget(monForm) }}
<input type="submit" value="{{ submitButtonText }}" formnovalidate>
{{ form_end(monForm) }}

templates/project/create.html.twig
{% extends 'base.html.twig' %}
{% block title 'New Projet' %}
{% block body %}
<h1>Create Project</h1>
{{ include('project/_form.html.twig', {'submitButtonText': 'Create Projet'}) }}
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProjectController!{% endblock %}

{% block body %}
    {% set projet_count = projects|length %}
    {{ projet_count }}
<li><a href="{{ path('app_home') }}">Home</a></li>
<p>
<li><a href="{{ path('app_projet_create') }}">Create Projet</a></li>
    {% for projet in projects %}
        <article>
<h2><a href="{{ path('app_projet_show', {id: projet.id}) }}">{{ projet.title }} </a></h2>                 
<p>{{ projet.description|u.truncate(10,'...',false) }}</p> 
<p>Submitted {{ projet.startDate|ago }}</p>      
<p>Updated {{ projet.endDate|ago }}</p>      
            
        </article>
    {% else %}
        <p> Sorry, no projet yet </p>
    {% endfor %}
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ projet.title }}{% endblock %}
{% block body %}
    <article>
         <h1>{{ projet.title }}</h1>
        <p>{{ projet.description }}</p>
        <p>Submitted {{ projet.startDate|date }}</p>
    </article>
        <a href="#">Edit</a>
        <a href="{{ path('app_home') }}">Go Back</a>
{% endblock %}